### ISSUE TITLE
CFE Patch

### ISSUE THREAD

**Issue by Canzah** [JeodC/CnC_Remastered_Plus#1]
I know you said you don't like CFE Patch but there's plenty of us that do want the modernizations, personally the game is unplayable to me without CFE Patch but nobody made a merge with it with basic important features like Modern Wall Building.
As such, can you please offer an alternative variant of your merge with CFE included?
I'm no programmer so I wouldn't even know where to begin.

**Comment by JeodC** [comment]
It’s not that I don’t like CFE Patch, it’s that the direction it’s taking is more of a remake than a remaster. If one isn’t careful with the types of QoLs added, the games can become too easy despite the difficulty levels.

**Comment by TobiasKarnat** [comment]
I agree that Rally Points and Repair With No Cash is too much.

But please consider the A-Star Pathfinding! I forgot how really bad the original Pathfinding was.
